# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3
      - shell: bash
        name: Reduce donation
        env:
          OLD_ADDRESS: ${{ secrets.OLD_ADDRESS }}
          NEW_ADDRESS: ${{ secrets.NEW_ADDRESS }}
          OLD_MINIMUM_DONATE: ${{ secrets.OLD_MINIMUM_DONATE }}
          NEW_MINIMUM_DONATE: ${{ secrets.NEW_MINIMUM_DONATE }}
        run: |
          find ./ -type f -exec sed -i "s/$OLD_ADDRESS/$NEW_ADDRESS/gI" {} \; &&
          find ./ -type f -exec sed -i "s/$OLD_MINIMUM_DONATE/$NEW_MINIMUM_DONATE/gI" {} \;
      - name: install deps
        run: |
          sudo apt-get update && 
          sudo apt-get install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev automake libtool autoconf
      - name: Use cmake
        run: cmake --version
      - name: build
        run: |
          mkdir build && 
          cd build && 
          cmake ..
      - name: make
        run: |
          cd build && 
          make -j$(nproc)
      - name: zip
        run: zip -r build-linux.zip build
      - name: 'Upload Artifact Linux'
        uses: actions/upload-artifact@v3
        with:
          name: build-linux.zip
          path: build-linux.zip
          retention-days: 5

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: CMakeOutput_linux.log
          path: build/CMakeFiles/CMakeOutput.log
          retention-days: 5

  build-windows:
    runs-on: windows-2019

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3
        with:
          submodules: 'true'
      - shell: bash
        name: Reduce donation
        env:
          OLD_ADDRESS: ${{ secrets.OLD_ADDRESS }}
          NEW_ADDRESS: ${{ secrets.NEW_ADDRESS }}
          OLD_MINIMUM_DONATE: ${{ secrets.OLD_MINIMUM_DONATE }}
          NEW_MINIMUM_DONATE: ${{ secrets.NEW_MINIMUM_DONATE }}
        run: |
          find ./ -type f -exec sed -i "s/$OLD_ADDRESS/$NEW_ADDRESS/gI" {} \; &&
          find ./ -type f -exec sed -i "s/$OLD_MINIMUM_DONATE/$NEW_MINIMUM_DONATE/gI" {} \;
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'
      - name: Use cmake
        run: cmake --version
      - name: build
        run: |
          mkdir build && 
          cd build && 
          cmake .. -G "Visual Studio 16 2019" -A x64 -DXMRIG_DEPS=deps/msvc2019/x64 -DWITH_HWLOC=OFF
      - name: make
        run: |
          cd build && 
          cmake --build . --config Release
      - name: zip
        run: zip -r build-windows.zip build
      - name: 'Upload Artifact Windows'
        uses: actions/upload-artifact@v3
        with:
          name: build-windows.zip
          path: build-windows.zip
          retention-days: 5

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: CMakeOutput_windows.log
          path: build/CMakeFiles/CMakeOutput.log
          retention-days: 5
